# Generated by Django 4.1.5 on 2023-01-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todos", "0004_alter_todoitem_task_alter_todolist_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="task",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="todolist",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
